name: Update Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to update (e.g., v0.8.1)'
        required: true
        type: string

jobs:
  call-external:
    uses: holtjma/shared_github_workflows/.github/workflows/update-release.yml@286c4ec0efbe7aac72a7149cfbd2a00f57457881
    permissions:
      contents: write
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
